events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        
        # Redirige las peticiones de usuarios al microservicio correspondiente
        location /api/usuarios/ {
            proxy_pass http://service-usuarios:3001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirige las peticiones de expedientes al microservicio correspondiente
        location /api/expedientes/ {
            proxy_pass http://service-expedientes:3002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Todo lo demás va al frontend
        location / {
            proxy_pass http://frontend:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}